---
id: JavascriptMinify
name: JavascriptMinify
full: JavaScript minification library
rescription: A library that wraps various javascript minification backends.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha2
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/log: ^3
      horde/util: ^3
